version: '3.9'

services:
  web:
    build: .
    container_name: web-test
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      # Variables opcionales si tu PHP necesita
      # DB_HOST: db
      # DB_NAME: demo
      # DB_USER: demo
      # DB_PASS: demo
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: db-test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
